### ISSUE TITLE
List 'The Commons Conservancy'

### ISSUE THREAD

**Issue by ecogit** [getnikola/nikola-users#14]
Hi Nikola team,
The website of the meaningful [The Commons Conservancy](https://commonsconservancy.org/) is built on your wonderful Free Software. It's looking good and quite comprehensive.
They should be on the list, eventually even be featured as a reference.

**Comment by Kwpolska** [comment]
This place isn’t meant for addition requests. Please file one [via the website itself](https://users.getnikola.com/add/) (and try to read the text on the page more carefully in the future).
