### ISSUE TITLE
Add Telugu language 

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola-users#9]
https://users.getnikola.com/add/ -> Languages

**Comment by Kwpolska** [comment]
If you can speak this language, perhaps you should [contribute some translations](https://www.transifex.com/ralsina/nikola/) to Nikola? It shouldn’t take you longer than 10 minutes.

In the meantime, I added Telugu to users.getnikola.com.

**Comment by ChillarAnand** [comment]
Sure :-)
